// Generated by https://quicktype.io

import { User } from "./user";

export interface Challenge {
  challenge_id: number;
  name: string;
  description: string;
  user_id: number;
  testcases: null;
  submission: null;
  user: User;
  submission_status: string;
}
