// Generated by https://quicktype.io

import { Challenge, ChallengeTestcase } from "./challenge";
import { User } from "./user";

export interface Submission {
  submission_id: number;
  language: string;
  source_code: string;
  status: string;
  user_id: number;
  user: User;
  challenge_id: number;
  challenge: Challenge;
  submission_testcases: SubmissionTestcase[];
}

export interface SubmissionTestcase {
  submission_testcase_id: number;
  status: string;
  output: string;
  submission_id: number;
  submission: null;
  challenge_testcase_id: number;
  challenge_testcase: ChallengeTestcase;
}
