// Generated by https://quicktype.io

export interface User {
  id: number;
  displayname: string;
  email: string;
  role: string;
}

export interface UserMeResponse {
  id: number;
  displayname: string;
  password: string;
  email: string;
  role: string;
}

export interface UserLoginResponse {
  token: string;
  userid: number;
  displayname: string;
  email: string;
  role: string;
}

export interface UserRegisterResponse {
  userid: number;
  displayname: string;
  email: string;
}
