export interface User {
  ID: number;
  DisplayName: string;
  Password: string;
  Email: string;
  Role: string;
  CreatedAt: string;
}

// Generated by https://quicktype.io

export interface UserMeResponse {
  id: number;
  displayname: string;
  password: string;
  email: string;
  role: string;
}
